Add tests
sensu-plugins/sensu-plugins-load-checks pull request #17
Opened 2017-08-24 11:35 UTC by barryorourke

My first attempt at adding tests to a plugin, I think everything should be covered.

2017-08-26 18:24 UTC, majormoses commented
I think I ran into this and solved this by locking some dependencies: https://github.com/sensu-plugins/sensu-plugins-dcos/blob/0.0.4/sensu-plugins-dcos.gemspec#L40-L41

2017-08-28 13:35 UTC, barryorourke commented
It's a bit of a messy pull request but I got there in the end. Never really done much more than hack together a quick script in Ruby, so it was a bit of a learning experience.

This only tests against 2.4.1 is that we are aiming for, or do we want to include more versions?

2017-08-28 16:52 UTC, majormoses commented
we should probably do more versions. @eheydrick do we want to tackle this now or should we just push out testing with just 2.4.1?

2017-09-09 16:46 UTC, majormoses commented on test/integration/default/serverspec/check-load_spec.rb
> +describe file(check) do
probably best to put all the common checks into something like a spec helper that can be called, here is an example: https://github.com/sensu-plugins/sensu-plugins-dcos/blob/0.1.1/test/integration/helpers/serverspec/shared_spec.rb

https://github.com/sensu-plugins/sensu-plugins-dcos/blob/0.1.1/test/integration/default/serverspec/check-dcos-component-health.rb_spec.rb#L10-L12

2017-09-12 06:24 UTC, eheydrick commented
I'd prefer to have testing on all ruby versions. Wondering if it would be possible to derive the kitchen suite version from the ruby version being tested in travis.

2017-09-12 07:09 UTC, majormoses commented
I went down that route originally but ran into issues that using the docker provisioner in travis you could not mount volumes.

2017-09-12 07:10 UTC, majormoses commented
We could maybe try making everything a shared tests then for each suite we just have some pretty bare includes and that's about it.

2017-09-19 19:18 UTC, majormoses commented
@barryorourke I figured out how to pretty easily tests all the versions in dcos you can check it out here: https://github.com/sensu-plugins/sensu-plugins-dcos/tree/0.3.0 and the PR with the changes: https://github.com/sensu-plugins/sensu-plugins-dcos/pull/10

2017-10-03 11:11 UTC, barryorourke commented
This should be ready to go now.

2017-10-03 19:13 UTC, majormoses requested changes
Looks great just need a changelog entry to detail ruby 2.0 removal. See [here](https://github.com/sensu-plugins/community/blob/master/HOW_WE_CHANGELOG.md#the-breaking-change) for information on how to inform on breaking changes.

2017-10-03 19:13 UTC, majormoses commented on sensu-plugins-load-checks.gemspec
> +  s.required_ruby_version  = '>= 2.1.0'
makes it a breaking change (which is OK as long as it called out appropriately in CHANGELOG and versioned.

2017-10-03 20:50 UTC, majormoses approved these changes

2017-10-03 20:50 UTC, merged

2017-10-03 21:14 UTC, majormoses commented
Will get a release out as soon as travis stops having issues: https://www.traviscistatus.com/incidents/p7sw6trycn41

2017-10-03 21:31 UTC, majormoses commented
released: https://rubygems.org/gems/sensu-plugins-load-checks/versions/4.0.0